language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t eminkazimov/docker-react -f Dockerfile.dev .   

script:
  - docker run -e CI=true eminkazimov/docker-react npm run test